### ISSUE TITLE
Estudo e validação de telas

### ISSUE THREAD

**Issue by DanielMandira** [Portfolio-Online-Fatec/PO-SistemaAcademico-Desktop#5]
- [x] Estudo e validação de telas criadas pelos squads 1, 2, 3 ( Controle de Qualidade UX/UI)

**Comment by JorgeMassaru** [comment]
Validação das telas feitas e enviadas para os designers. Estudo dos designs feitos e e apontamentos enviados.

**Comment by JorgeMassaru** [comment]
Retorno apenas da squad 2.
